### ISSUE TITLE
Pull from remote error: context deadline exceeded

### ISSUE THREAD

**Issue by fedeizzo** [nlewo/comin#24]
Hello, thanks for your work 👋 

I am encountering an error while pulling my repository (first setup).

Error
-----
```
...
INFO[0000] Pull from remote '<name>' failed: Get <url>: context deadline exceeded
DEBU[0000] Fetch done with repository.Repository{SelectedCommitId: ""...
DEBU[0000] The repository status is the same than the previous one
...
```
I think the context is [this one](https://github.com/nlewo/comin/blob/4fefa65aca41d797264b548b14bd153902a3cc1d/internal/repository/git.go#L132).

Comin version
--------------
`v0.1.1`

**Comment by nlewo** [comment]
Hello!

Yes, this timeout is too short! Sorry about this.

This PR should fixes your issue: https://github.com/nlewo/comin/pull/25

Ideally, let me know if this default value is enough for you (5 minutes to Git fetch).

**Comment by fedeizzo** [comment]
It's working, thank you 🥇
